### ISSUE TITLE
Hotlink error with latest babel

### ISSUE THREAD

**Issue by jfairley** [babel/babelify#100]
I just started seeing the following error message in my travis builds. It looks like it's a [very new change](https://github.com/babel/babel/commit/31c1286a3c9fdd7885c5e1974838b9b1e5a01327) to babel which doesn't like the way that babelify imports babel. That's my best guess anyway...

```
Error: Don't hotlink internal Babel files.
    at Object.exports.default (/home/travis/build/levelsbeyond/live-clipping-ui/node_modules/babelify/node_modules/babel-core/lib/babel/tools/protect.js:15:11)
    at Object.<anonymous> (/home/travis/build/levelsbeyond/live-clipping-ui/node_modules/babelify/node_modules/babel-core/lib/babel/api/node.js:42:28)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/levelsbeyond/live-clipping-ui/node_modules/babelify/index.js:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/levelsbeyond/live-clipping-ui/gulpfile.js:23:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/home/travis/build/levelsbeyond/live-clipping-ui/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/home/travis/build/levelsbeyond/live-clipping-ui/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/home/travis/build/levelsbeyond/live-clipping-ui/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/home/travis/build/levelsbeyond/live-clipping-ui/node_modules/gulp/node_modules/liftoff/index.js:185:9)
    at /home/travis/build/levelsbeyond/live-clipping-ui/node_modules/gulp/node_modules/liftoff/index.js:159:9
    at /home/travis/build/levelsbeyond/live-clipping-ui/node_modules/gulp/node_modules/v8flags/index.js:91:14
    at /home/travis/build/levelsbeyond/live-clipping-ui/node_modules/gulp/node_modules/v8flags/index.js:38:7
    at process._tickCallback (node.js:448:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:935:3
```

Here is my `npm install` output for babelify:

```
babelify@6.1.2 node_modules/babelify
├── object-assign@2.1.1
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
└── babel-core@5.6.8 (slash@1.0.0, path-is-absolute@1.0.0, path-exists@1.0.0, babel-plugin-remove-console@1.0.1, babel-plugin-remove-debugger@1.0.1, babel-plugin-eval@1.0.1, babel-plugin-jscript@1.0.1, babel-plugin-inline-environment-variables@1.0.1, babel-plugin-property-literals@1.0.1, fs-readdir-recursive@0.1.2, babel-plugin-react-constant-elements@1.0.3, babel-plugin-member-expression-literals@1.0.1, babel-plugin-undefined-to-void@1.1.6, shebang-regex@1.0.0, to-fast-properties@1.0.1, trim-right@1.0.0, babel-plugin-react-display-name@1.0.3, babel-plugin-constant-folding@1.0.1, strip-json-comments@1.0.2, babel-plugin-proto-to-assign@1.0.3, babel-plugin-dead-code-elimination@1.0.2, babel-plugin-runtime@1.0.7, private@0.1.6, globals@6.4.1, estraverse@4.1.0, esutils@2.0.2, convert-source-map@1.1.1, home-or-tmp@1.0.0, babel-plugin-undeclared-variables-check@1.0.2, js-tokens@1.0.1, line-numbers@0.2.0, debug@2.2.0, repeating@1.1.3, detect-indent@3.0.1, chalk@1.0.0, minimatch@2.0.8, output-file-sync@1.1.1, resolve@1.1.6, ast-types@0.7.6, is-integer@1.0.4, source-map-support@0.2.10, acorn-jsx@1.0.3, source-map@0.4.2, regenerator@0.8.31, core-js@0.9.18, regexpu@1.2.0)
```

**Comment by saitheexplorer** [comment]
Just started seeing this as well - having it on `v5.6.8` but `v5.6.7` is fine.

**Comment by zertosh** [comment]
It's also fine in v5.6.9+. Reinstalling babelify so that you get a newer version of babel-core fixes it. Sorry

**Comment by jfairley** [comment]
I can verify that my builds are working again. My last build used `v5.6.15`. Closing.
