### ISSUE TITLE
Unknown option `base._`

### ISSUE THREAD

**Issue by Julio-Guerra** [babel/babelify#129]
It seems I am not the only one to have the same problem (#125).

```
ReferenceError: [BABEL] [..] Unknown option: base._
[...]
at OptionManager.mergeOptions (node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:18)
```

Browserify passes non-option arguments under the `_` key of the option object.

My temporary workaround is to delete it `delete opts._;` [here](https://github.com/babel/babelify/blob/master/index.js#L54) as it is currently done with other browserify options (`_flags`, `basedir`, `global`).

**Comment by tomtom87** [comment]
+1 I just came here to write a support ticket on exactly teh same problem. I have not been able to use `babelify` yet due to this base._ error. The issue is in a module not my source so I am weary to touch it

**Comment by tomtom87** [comment]
```
 browserify -t [babelify] src/App.js > src/dist/App.js
ReferenceError: [BABEL] /home/top/react-p2p-chat/src/App.js: Unknown option: base._ while parsing file: /home/top/react-p2p-chat/src/App.js
    at Logger.error (/home/top/react-p2p-chat/node_modules/babelify/node_modules/babel-core/lib/transformation/file/logger.js:43:11)
    at OptionManager.mergeOptions (/home/top/react-p2p-chat/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:18)
    at OptionManager.init (/home/top/react-p2p-chat/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:395:10)
    at File.initOptions (/home/top/react-p2p-chat/node_modules/babelify/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/home/top/react-p2p-chat/node_modules/babelify/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/home/top/react-p2p-chat/node_modules/babelify/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at Babelify._flush (/home/top/react-p2p-chat/node_modules/babelify/index.js:28:24)
    at Babelify.<anonymous> (_stream_transform.js:118:12)
    at Babelify.g (events.js:260:16)
    at emitNone (events.js:67:13)
```

**Comment by matthiasak** [comment]
@tomtom87 @Julio-Guerra I managed to get some babelify working again with Babel v6 on node v4.2.1, but after upgrading to node v5, I had this issue when passing babel and browserify options via CLI/npm script.

What versions of node are you on?

**Comment by Julio-Guerra** [comment]
@matthiasak 
```sh
> npm version
{ Alpha: '0.1.0',
  npm: '3.3.9',
  ares: '1.10.1-DEV',
  http_parser: '2.6.0',
  icu: '55.1',
  modules: '46',
  node: '4.2.1',
  openssl: '1.0.2d',
  uv: '1.7.5',
  v8: '4.5.103.35',
  zlib: '1.2.8' }
```

**Comment by gabrielf** [comment]
I got the same error using babelify with some react code. After I had `npm install --save-dev babel-preset-react` and passed `--presets react` to babelify it failed with the `Unknown option base._` error.

For me the error went away when I specified the babelify options in `package.json`:

    "browserify": {
      "transform": [
        [
          "babelify",
          {
            "presets": ["react"]
          }
        ]
      ]
    }

instead of having them with the [ ] syntax on the command line.

This may not solve your problem though since you don't seem to specify any options to babelify...

Check out this minimal example which builds using browserify/babelify: https://github.com/gabrielf/minimal-react-project

**Comment by matthiasak** [comment]
@gabrielf So it didn't work if you split the babel options to it's own section in package.json?

```
"browserify": {
  "transform": ["babelify"]
},
"babel": {
  "presets": ["react"]
}
```

**Comment by zertosh** [comment]
Fixed in babelify@7.1.0

**Comment by gabrielf** [comment]
@zertosh Nice work! My project now builds even when specifying options using [ … ] on the command line.

@matthiasak Yeah, that worked to but specifying options on the command line didn't (but with 7.1.0 it does)

**Comment by tomtom87** [comment]
@zertosh nice one yeh working now

**Comment by WenXuanYuan** [comment]
How did you guys solve this problem, when I try to run my application. also an occurred like this . here is the error : 
ERROR in ./src/App.js
Module build failed: ReferenceError: [BABEL] /Users/www/Documents/pppp/src/App.js: Unknown option: base.optional
    at Logger.error (/Users/www/Documents/pppp/node_modules/babel-core/lib/transformation/file/logger.js:43:11)
    at OptionManager.mergeOptions (/Users/www/Documents/pppp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:18)
    at OptionManager.init (/Users/www/Documents/pppp/node_modules/babel-core/lib/transformation/file/options/option-manager.js:396:10)
    at File.initOptions (/Users/www/Documents/pppp/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/Users/www/Documents/pppp/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/Users/www/Documents/pppp/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transpile (/Users/www/Documents/pppp/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/www/Documents/pppp/node_modules/babel-loader/index.js:69:12)
 @ multi app

Please give me  some help ! thank you .

**Comment by zertosh** [comment]
@WenXuanYuan `optional` isn't a valid option anymore. babelify 7.0 uses babel 6.0 and things changed a lot. Please read the README.

**Comment by niftylettuce** [comment]
How do you solve this?

**Comment by zertosh** [comment]
@niftylettuce what error are you getting? The issue is resolved

**Comment by niftylettuce** [comment]
![screen shot 2015-11-08 at 2 12 35 am](https://cloud.githubusercontent.com/assets/523141/11019260/384191d8-85be-11e5-8faf-c4ef6462321e.png)

**Comment by niftylettuce** [comment]
Unknown option: base.stage

**Comment by niftylettuce** [comment]
Unknown option: base.optional

**Comment by niftylettuce** [comment]
I really, really dislike how the authors of your package don't even bother to put a DEPRECATE NPM notice in the packages.

**Comment by matthiasak** [comment]
@niftylettuce

The `stage` and `optional` flags are no longer valid options to babelify... not due to babelify, but due to babel.

**Comment by niftylettuce** [comment]
So what are their replacements?

**Comment by zertosh** [comment]
@niftylettuce Please read the README

**Comment by matthiasak** [comment]
I suggest you read the Babel docs. They've even posted a blog about this: https://babeljs.io/blog/2015/10/31/setting-up-babel-6/.

**Comment by niftylettuce** [comment]
But there's no deprecate notice, so to find out why this errors I have to go searching online.

**Comment by zertosh** [comment]
There was a major version bump. That's sufficient notice.

**Comment by niftylettuce** [comment]
What has the optional flag been replaced with?  This only mentions `stage` https://babeljs.io/blog/2015/10/31/setting-up-babel-6/.

**Comment by zertosh** [comment]
That's not how plugins work anymore. Please read the documentation and open a new issue in the appropriate forum.
