### ISSUE TITLE
Transpiling expressjs causes calls to `new global.XMLHttpRequest()`

### ISSUE THREAD

**Issue by m0ru** [babel/babelify#158]
I wanted to try and play around a bit with es6 on node/express for building isomorphic/universal apps: 

<https://github.com/m0ru/isomorphic_universal-app-test>. 

The setup currently uses the following versions:
```
babelify: 7.2.0
browserify: 12.0.1
babel-preset-es2016-node5: 1.1.2
express: 4.13.3
node: 5.1.0
npm: 3.3.12
```
Running `browserify -t babelify index.js -o build/compiled.js` with a `.babelrc` of `{'presets': ['es2016-node5']}` ends up generating `var xhr = new global.XMLHttpRequest()` and `var xhr = self._xhr = new global.XMLHttpRequest()` from the expressjs-sources which fails when running the script via `node build/compiled.js`. Express is included es6-style (`import 'express';`)

**Comment by m0ru** [comment]
If you clone the repo above, comment in `index.js:5` and run `npm install && npm start` you should get something like the following  output:
```
$ npm start

> isomorphic_universal-app-test@0.0.1 prestart C:\DATA\ksinger\Playground\isomorphic_universal-app-test
> npm run build


> isomorphic_universal-app-test@0.0.1 build C:\DATA\ksinger\Playground\isomorphic_universal-app-test
> browserify -t babelify index.js -o build/compiled.js


> isomorphic_universal-app-test@0.0.1 start C:\DATA\ksinger\Playground\isomorphic_universal-app-test
> node build/compiled.js

import working
C:\DATA\ksinger\Playground\isomorphic_universal-app-test\build\compiled.js:21839
var xhr = new global.XMLHttpRequest()
          ^

TypeError: global.XMLHttpRequest is not a function
    at Object.<anonymous> (C:\DATA\ksinger\Playground\isomorphic_universal-app-test\build\compiled.js:21839:11)
    at Object.__dirname.227 (C:\DATA\ksinger\Playground\isomorphic_universal-app-test\build\compiled.js:21872:4)
    at s (C:\DATA\ksinger\Playground\isomorphic_universal-app-test\build\compiled.js:1:316)
    at C:\DATA\ksinger\Playground\isomorphic_universal-app-test\build\compiled.js:1:367
    at Object.<anonymous> (C:\DATA\ksinger\Playground\isomorphic_universal-app-test\build\compiled.js:21876:18)
    at Object.__dirname.228../capability (C:\DATA\ksinger\Playground\isomorphic_universal-app-test\build\compiled.js:22151:4)
    at s (C:\DATA\ksinger\Playground\isomorphic_universal-app-test\build\compiled.js:1:316)
    at C:\DATA\ksinger\Playground\isomorphic_universal-app-test\build\compiled.js:1:367
    at Object.__dirname.226../lib/request (C:\DATA\ksinger\Playground\isomorphic_universal-app-test\build\compiled.js:21755:21)
    at s (C:\DATA\ksinger\Playground\isomorphic_universal-app-test\build\compiled.js:1:316)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Bin\\nodejs\\node.exe" "C:\\Bin\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! isomorphic_universal-app-test@0.0.1 start: `node build/compiled.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the isomorphic_universal-app-test@0.0.1 start script 'node build/compiled.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the isomorphic_universal-app-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/compiled.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls isomorphic_universal-app-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\DATA\ksinger\Playground\isomorphic_universal-app-test\npm-debug.log
```

**Comment by zertosh** [comment]
This isn't a babelify issue. It's how browserify works. It [shims](https://github.com/substack/node-browserify#compatibility) the core [http](https://nodejs.org/api/http.html) module with [stream-http](https://github.com/jhiesey/stream-http) for browser compatibility. Browserify has a `--node` flag to prevent this from happening. Take a look at their docs for more info.

**Comment by m0ru** [comment]
Thx a lot! :)
