### ISSUE TITLE
Plugin lookup path

### ISSUE THREAD

**Issue by tmcw** [babel/babelify#159]
I'm trying to update [documentation.js to babel 6](https://github.com/documentationjs/documentation/pull/218): one of the issues I'm seeing is this:

```
/Users/tmcw/src/documentation/bin/documentation.js:32
    throw err;
    ^

ReferenceError: Unknown plugin "es2015" specified in "base" at 0, attempted to resolve relative to "/Users/tmcw/src/documentation/test/fixture" while parsing file: /Users/tmcw/src/documentation/test/fixture/es6.input.js
    at /Users/tmcw/src/documentation/node_modules/babel-core/lib/transformation/file/options/option-manager.js:193:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/tmcw/src/documentation/node_modules/babel-core/lib/transformation/file/options/option-manager.js:173:20)
    at OptionManager.mergeOptions (/Users/tmcw/src/documentation/node_modules/babel-core/lib/transformation/file/options/option-manager.js:271:36)
    at OptionManager.init (/Users/tmcw/src/documentation/node_modules/babel-core/lib/transformation/file/options/option-manager.js:416:10)
    at File.initOptions (/Users/tmcw/src/documentation/node_modules/babel-core/lib/transformation/file/index.js:190:75)
    at new File (/Users/tmcw/src/documentation/node_modules/babel-core/lib/transformation/file/index.js:121:22)
    at Pipeline.transform (/Users/tmcw/src/documentation/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at Babelify._flush (/Users/tmcw/src/documentation/node_modules/babelify/index.js:28:24)
    at Babelify.<anonymous> (_stream_transform.js:118:12)
```

I want to use babelify and presets as a module in a binary package: so there's a file at, say, `lib/lookup.js` that uses `babelify`'s node interface and configures it with presets. How do I tell babelify where to look for presets?

**Comment by jmm** [comment]
I think presets are resolved relative to the `.babelrc` file or CWD. But if you're configuring it via Node you should be able to also just require in the preset if you need to, e.g. `.transform(babelify, {presets: [require("/some/path")]})`. Are you sure the issue you're running into isn't just specifying it as a plugin instead of a preset?: `Unknown plugin "es2015"`

**Comment by hzoo** [comment]
Yeah left a comment https://github.com/documentationjs/documentation/pull/218/files#diff-a08870f220163e859218e0fd2a065dcaR29

**Comment by jmm** [comment]
@hzoo Just saw that :+1:

**Comment by cherrydev** [comment]
While that workaround (requiring the plugins in node and passing them instead of the name of the plugin) seems to work fine for most purposes, it appears to be impossible to get 'transform-runtime' working if that module can't be resolved from the directory the source file is inside.
`Error: Cannot find module 'babel-runtime/helpers/classCallCheck' from <foreign path>`.  I'm frustrated that there's no way to get babelify to resolve plugins from a specific directory.

**Comment by dschissler** [comment]
This appears to be a block for my webpack setup.  I recently upgraded postfix and cssnext to the next major version and it also stopped being able to find things so I had to again pass in the paths to resolve from.  I'm not sure if this is a babel webpack issue but it seems to be affecting both browserify and webpack.

* app
  * webpack
    * entries
    * commons
    * modules
* dev
  * gulpfile.js
  * node_modules
  * bower_components
  * vendor

**Comment by zertosh** [comment]
Hm, I don't think babelify can help with plugin path resolution - that's just how babel works.
