### ISSUE TITLE
Another "'import' and 'export' may appear only with 'sourceType: module'" related issue

### ISSUE THREAD

**Issue by RevillWeb** [babel/babelify#186]
Hi,

I'm trying to transform a simple ES2015 application using babelify and I'm getting the following error:

> export class RebelRouter extends HTMLElement {
> ^
> ParseError: 'import' and 'export' may appear only with 'sourceType: module'

I am using the following CLI command:

`
browserify -e src/app.js -o dist/bundle.js -t [ babelify --presets [ es2015 ] --plugins [ transform-class-properties ]]
`

I am using the latest version of babel, browserify and babelify.

Transformation with babel alone works perfectly fine.

I've also looked at the other similar issues for this project but none of the solutions appear to work for me.

Any help would be greatly appreciated,

Thank you.

**Comment by zertosh** [comment]
I don't see anything immediately obvious except the spacing in the brackets - unless that's bad copy/paste, it would explain why babel isn't getting your options, and thus not transpiling.

```
 -t [ babelify --presets [ es2015 ] --plugins [ transform-class-properties ] ]
                                                that space is significant   ^
```

**Comment by pke** [comment]
Same issue here with 7.2.0. Works with 6.4.0

**Comment by zertosh** [comment]
@pke: you have a `.babelrc` but your `bundle` npm script still needs to at least pass `-t babelify`.

**Comment by kileras** [comment]
I just end up in this situation today, isn't the case that having a "browserify" section in the package.json  with the babelify transform enough?

**Comment by loganfsmyth** [comment]
@kileras Yes as long as you have a `.babelrc` to configure Babel too.

Another common cause of this issue is that you have ES6 files in other modules that are dependencies of your modules. Cases like that are harder to solve since browserify transforms do not run on dependencies by default.

**Comment by kileras** [comment]
Yeah also will be valid is you pass the options to the babelify transform isntead of ".babelrc". 

In my case I was using some local modules with 'npm link' and apparently something changed in browserify 12.1.0 (I missed like 4 major versions since I used last time 😄 ) and it wasn't applying the transforms. I manage to solve it by using "pathmodify" to load that modules without them being in "node_modules" and the transforms are applied to them and also I tried adding the "browserify" seciton in the package.json of those same modules and then even with npm link it does it 😄

**Comment by mkapiczy** [comment]
The error occures in documentationjs module, and was reported in documentationjs/documentation#950 . However, I believe it may be babelify bug. Therefore I'd like to provide information on documentationjs configuration, and babelify usage. Maybe it might help in identifying the issue.

My error:

```
npm run docs

> cuesta@0.8.1 docs /builds/project-0
> node ./node_modules/.bin/documentation build ./src/services/index.js --output ./docs --format html --config .documentation.yml --github

Error: Parsing file /builds/project-0/src/services/Auth.js: 'import' and 'export' may appear only with 'sourceType: module' (11:0)
    at Deps.parseDeps (/builds/project-0/node_modules/module-deps-sortable/index.js:467:28)
    at fromSource (/builds/project-0/node_modules/module-deps-sortable/index.js:402:44)
    at /builds/project-0/node_modules/module-deps-sortable/index.js:396:17
    at ConcatStream.<anonymous> (/builds/project-0/node_modules/module-deps-sortable/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:165:20)
    at finishMaybe (/builds/project-0/node_modules/module-deps-sortable/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:475:14)
    at endWritable (/builds/project-0/node_modules/module-deps-sortable/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:485:3)
    at ConcatStream.Writable.end (/builds/project-0/node_modules/module-deps-sortable/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:455:41)
    at DuplexWrapper.onend (/builds/project-0/node_modules/readable-stream/lib/_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:255:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cuesta@0.8.1 docs: `node ./node_modules/.bin/documentation build ./src/services/index.js --output ./docs --format html --config .documentation.yml --github`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cuesta@0.8.1 docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-20T12_37_07_578Z-debug.log

```
package.json

```
{
  "name": "documentation",
  "description": "a documentation generator",
  "version": "5.4.0",
  "author": "Tom MacWright",
  "bin": {
    "documentation": "./bin/documentation.js"
  },
  "dependencies": {
    "ansi-html": "^0.0.7",
    "babel-core": "^6.26.0",
    "babel-generator": "^6.26.0",
    "babel-plugin-system-import-transformer": "3.1.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-traverse": "^6.26.0",
    "babel-types": "^6.26.0",
    "babelify": "^8.0.0",
    "babylon": "^6.18.0",
    "chalk": "^2.3.0",
    "chokidar": "^2.0.0",
    "concat-stream": "^1.6.0",
    "disparity": "^2.0.0",
    "doctrine-temporary-fork": "2.0.0-alpha-allowarrayindex",
    "get-port": "^3.2.0",
    "git-url-parse": "^8.0.0",
    "github-slugger": "1.2.0",
    "glob": "^7.1.2",
    "globals-docs": "^2.4.0",
    "highlight.js": "^9.12.0",
    "js-yaml": "^3.10.0",
    "lodash": "^4.17.4",
    "mdast-util-inject": "^1.1.0",
    "micromatch": "^3.1.5",
    "mime": "^2.2.0",
    "module-deps-sortable": "4.0.6",
    "parse-filepath": "^1.0.2",
    "pify": "^3.0.0",
    "read-pkg-up": "^3.0.0",
    "remark": "^9.0.0",
    "remark-html": "7.0.0",
    "remark-toc": "^5.0.0",
    "remote-origin-url": "0.4.0",
    "shelljs": "^0.8.1",
    "stream-array": "^1.1.2",
    "strip-json-comments": "^2.0.1",
    "tiny-lr": "^1.1.0",
    "unist-builder": "^1.0.2",
    "unist-util-visit": "^1.3.0",
    "vfile": "^2.3.0",
    "vfile-reporter": "^4.0.0",
    "vfile-sort": "^2.1.0",
    "vinyl": "^2.1.0",
    "vinyl-fs": "^3.0.2",
    "yargs": "^9.0.1"
  },
  "devDependencies": {
    "are-we-flow-yet": "^1.0.0",
    "babel-cli": "^6.26.0",
    "babel-eslint": "^8.2.1",
    "babel-jest": "^22.1.0",
    "babel-plugin-syntax-async-functions": "^6.13.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.0",
    "babel-preset-flow": "^6.23.0",
    "chdir": "0.0.0",
    "coveralls": "^3.0.0",
    "cz-conventional-changelog": "2.1.0",
    "documentation-schema": "0.0.1",
    "eslint": "^4.16.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-flowtype": "^2.41.0",
    "flow-bin": "^0.64.0",
    "fs-extra": "^5.0.0",
    "husky": "^0.14.3",
    "jest": "^22.1.4",
    "json-schema": "0.2.3",
    "lint-staged": "^6.0.1",
    "mock-fs": "^4.4.2",
    "p-event": "^1.3.0",
    "prettier": "^1.10.2",
    "regenerator-runtime": "^0.11.1",
    "standard-version": "^4.3.0",
    "tmp": "^0.0.33"
  },
  "keywords": [
    "documentation",
    "formatter",
    "jsdoc",
    "jsdoc3",
    "parser",
    "website"
  ],
  "license": "ISC",
  "main": "lib/index.js",
  "repository": {
    "type": "git",
    "url": "git@github.com:documentationjs/documentation.git"
  },
  "scripts": {
    "build": "rm -rf lib && babel -D src -d lib && npm run doc",
    "release": "standard-version",
    "precommit": "lint-staged",
    "prepublish": "npm run build",
    "format": "prettier --write '{src,__tests__,declarations,bin,default_theme}/**/*.js' --single-quote",
    "doc": "node ./bin/documentation.js build src/index.js -f md --access=public > docs/NODE_API.md",
    "self-lint": "node ./bin/documentation.js lint src",
    "test": "npm run build && eslint . && are-we-flow-yet src && flow check && jest",
    "test-ci": "npm run build && eslint . && are-we-flow-yet src && flow check && jest --runInBand"
  },
  "jest": {
    "testPathIgnorePatterns": [
      "/node_modules/",
      "utils.js",
      "fixture"
    ],
    "coveragePathIgnorePatterns": [
      "<rootDir>/lib/"
    ],
    "collectCoverage": true,
    "testEnvironment": "node"
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
  "engines": {
    "node": ">=4"
  },
  "lint-staged": {
    "*.js": [
      "prettier --write --single-quote",
      "git add"
    ]
  },
  "greenkeeper": {
    "ignore": [
      "remote-origin-url"
    ]
  }
}
```

.babelrc

```
{
  "presets": [
    ["env", {
      "targets": {
      "node": 4
      },
      "include": ["transform-regenerator"]
    }],
    "flow"
  ],
  "plugins": ["syntax-async-functions"],
  "ignore": [
      "**/default_theme/assets/*"
  ]
}
```

File where the error is born:

```
const mdeps = require('module-deps-sortable');
const path = require('path');
const babelify = require('babelify');
const concat = require('concat-stream');
const moduleFilters = require('../module_filters');
const smartGlob = require('../smart_glob.js');

/**
 * Returns a readable stream of dependencies, given an array of entry
 * points and an object of options to provide to module-deps.
 *
 * This stream requires filesystem access, and thus isn't suitable
 * for a browser environment.
 *
 * @param indexes paths to entry files as strings
 * @param config optional options passed
 * @returns results
 */
function dependencyStream(
  indexes: Array<string>,
  config: DocumentationConfig
): Promise<Array<SourceFile>> {
  const md = mdeps({
    /**
     * Determine whether a module should be included in documentation
     * @param {string} id path to a module
     * @returns {boolean} true if the module should be included.
     */
    filter: id => !!config.external || moduleFilters.internalOnly(id),
    extensions: []
      .concat(config.requireExtension || [])
      .map(ext => '.' + ext.replace(/^\./, ''))
      .concat(['.js', '.json', '.es6', '.jsx']),
    transform: [
      babelify.configure({
        sourceMap: false,
        compact: false,
        presets: [
          require('babel-preset-env'),
          require('babel-preset-stage-0'),
          require('babel-preset-react')
        ],
        plugins: [
          require('babel-plugin-transform-decorators-legacy').default,
          // Required to support webpack's System.import
          // https://github.com/documentationjs/documentation/issues/578
          require('babel-plugin-system-import-transformer').default
        ]
      })
    ],
    postFilter: moduleFilters.externals(indexes, config)
  });
  smartGlob(indexes, config.parseExtension).forEach(index => {
    md.write(path.resolve(index));
  });
  md.end();

  return new Promise((resolve, reject) => {
    md.once('error', reject);
    md.pipe(
      concat(function(inputs) {
        resolve(
          inputs
            .filter(
              input =>
                // At this point, we may have allowed a JSON file to be caught by
                // module-deps, or anything else allowed by requireExtension.
                // otherwise module-deps would complain about
                // it not being found. But Babel can't parse JSON, so we filter non-JavaScript
                // files away.
                config.parseExtension.indexOf(
                  path.extname(input.file).replace(/^\./, '')
                ) > -1
            )
            .map(input => {
              // remove source file, since it's transformed anyway
              delete input.source;
              return input;
            })
        );
      })
    );
  });
}

module.exports = dependencyStream;

```

What's interesting when I generate documentation in my local environment with the same command it works, but it does not in my docker container.
My local env:
OS: OSX
Node: 9.5.0
npm: 5.6.0

The docker image: https://hub.docker.com/r/mkapiczy/docker-java-node-chrome/

The error occured after webpack upgrade (from version 1 -> 3), but the project build and all tests run fine.

**Comment by OutThisLife** [comment]
wow the spaces actually matter.

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babelify. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.
