### ISSUE TITLE
Error EISDIR when browserifing and babelifing

### ISSUE THREAD

**Issue by indianscout** [babel/babelify#193]
Browserification with babelify plugins fails with the following error:
```
~/infektweb/guidelines.v4/dbdata/utils/stateFromHTML$ node transpile.js 
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read while parsing file: /home/indianscout/infektweb/guidelines.v4/dbdata/utils/stateFromHTML/test.js
    at Error (native)
    at Object.fs.readSync (fs.js:603:19)
    at Object.fs.readFileSync (fs.js:438:24)
    at OptionManager.addConfig (/home/indianscout/infektweb/guidelines.v4/dbdata/utils/stateFromHTML/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:196:35)
    at OptionManager.findConfigs (/home/indianscout/infektweb/guidelines.v4/dbdata/utils/stateFromHTML/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:16)
    at OptionManager.init (/home/indianscout/infektweb/guidelines.v4/dbdata/utils/stateFromHTML/node_modules/babelify/node_modules/babel-core/lib/transformation/file/options/option-manager.js:461:12)
    at File.initOptions (/home/indianscout/infektweb/guidelines.v4/dbdata/utils/stateFromHTML/node_modules/babelify/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/home/indianscout/infektweb/guidelines.v4/dbdata/utils/stateFromHTML/node_modules/babelify/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (/home/indianscout/infektweb/guidelines.v4/dbdata/utils/stateFromHTML/node_modules/babelify/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
    at Babelify._flush (/home/indianscout/infektweb/guidelines.v4/dbdata/utils/stateFromHTML/node_modules/babelify/index.js:28:24)

```

My node/npm/browserify versions:

> ~/infektweb/guidelines.v4/dbdata/utils/stateFromHTML$ npm --version
> 2.14.7
> ~/infektweb/guidelines.v4/dbdata/utils/stateFromHTML$ node --version
> v4.2.3
> ~/infektweb/guidelines.v4/dbdata/utils/stateFromHTML$ cat node_modules/browserify/package.json 
> {
>   "name": "browserify",
>   "version": "13.0.0",
>   "description": "browser-side require() the node way",
>   "main": "index.js",

The error can be reproduced with the following scripts:
transpile.js:
```javascript
var fs = require("fs");
var browserify = require("browserify");
browserify("./test.js")
  .transform("babelify", {
      presets: ["es2015"],
      plugins: ["transform-class-properties", "transform-object-rest-spread", "transform-array-from"]
  })
  .bundle()
  .pipe(fs.createWriteStream("bundle.js"));
```

test.js:
```javascript
module.exports = {
    test: function(){
      return null;
    }
}
``` 

My directory structure:
```
~/infektweb/guidelines.v4/dbdata/utils/stateFromHTML$ ls -al
total 176
drwxrwxr-x  3 indianscout indianscout 4096 Apr  4 16:40 .
drwxrwxr-x  4 indianscout indianscout 4096 Apr  4 12:46 ..
-rw-rw-r--  1 indianscout indianscout   68 Apr  4 16:40 test.js
-rw-rw-r--  1 indianscout indianscout  305 Apr  4 16:40 transpile.js
```

**Comment by loganfsmyth** [comment]
Babel looks for `.babelrc` in parent directories too. It sounds like you have a `.babelrc` that is a directory instead of a file somewhere in the parent path?

**Comment by indianscout** [comment]
Yes you are right, there was actually an .babelrc directory at the top level of my project.
A question: why does babel looks up .babelrc when I provide the babel configuration in transform() - like:
```
.transform("babelify", {
      presets: ["es2015"],
      plugins: ["transform-class-properties", "transform-object-rest-spread", "transform-array-from"]
  })
```

**Comment by loganfsmyth** [comment]
Babel searches for config relative to each file it processes, unless you tell it not to, explicitly passed-in config is just merged onto whatever was found. Specifying your config as a transform argument isn't something I'd personally recommend. Always use a `.babelrc` unless you have a good reason not to.
