### ISSUE TITLE
Syntax error "Unexpected token / while parsing file"

### ISSUE THREAD

**Issue by akrishnamurthy-zscaler** [babel/babelify#195]
Im trying to use babelify with browserify. The code is pretty simple. Here is my package.json

<pre>{
  "name": "newweb",
  "version": "1.0.0",
  "description": "new web ui",
  "main": "init.jsx",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "browserify -t [ babelify --presets [ es2015 react ] ] -e init.jsx -o bundle.js"
  },
  "keywords": [
    "web"
  ],
  "author": "newbie developer",
  "license": "MIT",
  "dependencies": {
    "react": "^15.0.1",
    "react-dom": "^15.0.1"    
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babelify": "^7.3.0",
    "browserify": "^13.0.0"
  }
}
</pre>

And here is my init.jsx
<pre>
import React from 'react';
import {render} from 'react-dom';

let App = () => {
	return (
		<h1>Hello World</h1>
	);
}

render((
	<App />
), document.getElementById('app'))
</pre>

When i run "npm run build", I get the error 

SyntaxError: /home/my/package.json: Error while parsing JSON - Unexpected token / while parsing file: /home/my/newweb/init.jsx
    at Object.parse (native)
    at OptionManager.addConfig (/home/my/newweb/node_modules/babel-core/lib/transformation/file/options/option-manager.js:200:62)
    at OptionManager.findConfigs (/home/my/newweb/node_modules/babel-core/lib/transformation/file/options/option-manager.js:419:30)
    at OptionManager.init (/home/my/newweb/node_modules/babel-core/lib/transformation/file/options/option-manager.js:461:12)
    at File.initOptions (/home/my/newweb/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/home/my/newweb/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (/home/my/newweb/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
    at Babelify._flush (/home/my/newweb/node_modules/babelify/index.js:27:24)
    at Babelify.<anonymous> (_stream_transform.js:118:12)
    at Babelify.g (events.js:260:16)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v4.1.1
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! newweb@1.0.0 build: `browserify -t [ babelify --presets [ es2015 react ] ] -e init.jsx -o bundle.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the newweb@1.0.0 build script 'browserify -t [ babelify --presets [ es2015 react ] ] -e init.jsx -o bundle.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the newweb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify -t [ babelify --presets [ es2015 react ] ] -e init.jsx -o bundle.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs newweb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls newweb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/my/newweb/npm-debug.log

**Comment by akrishnamurthy-zscaler** [comment]
turns out I had a typo :-(
