### ISSUE TITLE
Configuration in s-templates.json caused `Function Deployment Failed`

### ISSUE THREAD

**Issue by ch33hau** [babel/babelify#207]
Hi,

I'm trying to DRYer my `s-function.json` by grouping the same configuration into `s-templates.json`.

```
// s-templates.json
  ...
  "babelifyOptions": {
    "exclude": ["aws-sdk"],
    "transforms": [{
      "name": "babelify",
      "opts": {
        "presets": ["es2015"],
        "plugins": ["syntax-async-functions", "transform-regenerator"]
      }
    }],
    "minify": false
  },
  "customTemplateForBabelify": {
    "excludePatterns": [
      "node_modules"
    ],
    "optimize": "$${babelifyOptions}"
  },
  ...
```

When comes to s-function.json, 
```
// Working fine
"custom": "$${customTemplateForBabelify}",
```
is working fine for me. 

However, if I specifically inject the template to `optimize` field like below:
```
// Not working
"custom": {
  "excludePatterns": [
    "node_modules"
  ],
  "optimize": "$${babelifyOptions}"
}
```
Then I will get below errors:
```
/home/cheehau/opt/node/node-v6.3.0-linux-x64/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

ServerlessError: Function Deployment Failed
    at new ServerlessError (/home/cheehau/opt/node/node-v6.3.0-linux-x64/lib/node_modules/serverless/lib/Error.js:17:11)
    at FunctionDeploy.<anonymous> (/home/cheehau/opt/node/node-v6.3.0-linux-x64/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:126:19)
    at next (/home/cheehau/opt/node/node-v6.3.0-linux-x64/lib/node_modules/serverless/node_modules/rimraf/rimraf.js:74:7)
    at FSReqWrap.CB [as oncomplete] (/home/cheehau/opt/node/node-v6.3.0-linux-x64/lib/node_modules/serverless/node_modules/rimraf/rimraf.js:110:9)
From previous event:
    at FunctionDeploy.functionDeploy (/home/cheehau/opt/node/node-v6.3.0-linux-x64/lib/node_modules/serverless/lib/actions/FunctionDeploy.js:105:10)
...
```

I'm assuming both configurations should be the exactly the same, but one succeed and one failed.
Not sure if this should be fixed.

**Comment by ch33hau** [comment]
Update:

Although the first configuration was deploy-able, however it doesn't working during run-time, errors like below:

```
"errorMessage":"Unexpected reserved word",
"errorType":"SyntaxError",
"stackTrace":[
  "Module._compile (module.js:373:25)",
  "Object.Module._extensions..js (module.js:416:10)",
  "Module.load (module.js:343:32)",
  "Function.Module._load (module.js:300:12)",
  "Module.require (module.js:353:17)",
  "require (internal/module.js:12:17)",
  "Object.<anonymous> (/var/task/_serverless_handler.js:15:29)",
  "Module._compile (module.js:409:26)",
  "Object.Module._extensions..js (module.js:416:10)"
]
```

Which means, I don't have a way to DRYer it?

**Comment by ch33hau** [comment]
Just figured out that I'm created the issue in the wrong place. Apologies!!
