### ISSUE TITLE
Issue with dot-delineated file names

### ISSUE THREAD

**Issue by jdu** [babel/babelify#208]
Babel: 6.5.2
babel-core: 6.4.5
babel-preset-react: 6.11.1

I have a project which I started a long while back that's fairly large in size using React. I started using Babelify on it a few months back. Recently I did a bit of a refactor where I changed to loading React and ReactDOM within the client-side instead of requiring it in the client-side libs themselves.

This change immediately caused some issues. Babelify would no longer convert the JSX in my js files. To be clear, the only change I made was I removed `var React = require('react')` from all of my JS files in the repository.

I currently use browserify/watchify for development using a custom Makefile:

```
PATH := ../node_modules/.bin:$(PATH)
SHELL := /bin/bash
BIN = ../node_modules/.bin

watch:
    @$(BIN)/watchify -t [babelify] -o bundle.js -v -d .

build:
    NODE_ENV=production $(BIN)/browserify -t [babelify] app.js | uglifyjs -cm > bundle.min.js

dev:
    @$(BIN)/browserify -t [ babelify ] app.js > bundle.js

test:
    @$(BIN)/jest

clean:
    rm bundle.js || true
    rm bundle.min.js || true
```

And I have a `.babelrc` as well:

```
{"presets": ["react", "stage-1", "es2015"]}
```

As soon as I tried to either `make build` or `make watch` on the app, it started choking on JSX in the files whereas it hadn't before.

```
NODE_ENV=production ../node_modules/.bin/browserify -t [babelify ] app.js | uglifyjs -cm > bundle.min.js
SyntaxError: /<file_path>/common/components/ide/VertTab.react.js: Unexpected token (21:12)
  19 | 
  20 |         return (
> 21 |             <div className={className} onClick={this._onClick}>
     |             ^
  22 |                 <i className={iconClass}></i>&nbsp;{this.props.label}
  23 |             </div>
  24 |         )
    at Parser.pp.raise (/<file_path>/node_modules/babel-core/node_modules/babylon/index.js:1425:13)
    at Parser.pp.unexpected (/<file_path>/node_modules/babel-core/node_modules/babylon/index.js:2907:8)
    at Parser.pp.parseExprAtom (/<file_path>/node_modules/babel-core/node_modules/babylon/index.js:754:12)
    at Parser.pp.parseExprSubscripts (/<file_path>/node_modules/babel-core/node_modules/babylon/index.js:509:19)
    at Parser.pp.parseMaybeUnary (/<file_path>/node_modules/babel-core/node_modules/babylon/index.js:489:19)
    at Parser.pp.parseExprOps (/<file_path>/node_modules/babel-core/node_modules/babylon/index.js:420:19)
    at Parser.pp.parseMaybeConditional (/<file_path>/node_modules/babel-core/node_modules/babylon/index.js:402:19)
    at Parser.pp.parseMaybeAssign (/<file_path>/node_modules/babel-core/node_modules/babylon/index.js:365:19)
    at Parser.pp.parseParenAndDistinguishExpression (/<file_path>/node_modules/babel-core/node_modules/babylon/index.js:827:26)
    at Parser.pp.parseExprAtom (/<file_path>/node_modules/babel-core/node_modules/babylon/index.js:713:19)
```

I traced this down to the fact my files that contain react components are named with the suffix `.react.js`.

I can resolve it by modifying my commands in the Makefile to include `--extensions .react.js` but if I try to modify my .babelrc to include extensions, babelify chokes on the setting:

Modified .babelrc

`{"presets": ["react", "stage-1", "es2015"], "extensions": [".react.js"]}`

Babelify error output

```
NODE_ENV=production ../node_modules/.bin/browserify -t [babelify] app.js | uglifyjs -cm > bundle.min.js
ReferenceError: [BABEL] /<file_path>/accounts/app.js: Unknown option: /<file_path>/accounts/.babelrc.extensions while parsing file: /<file_path>/accounts/app.js
    at Logger.error (/<file_path>/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/<file_path>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:262:18)
    at OptionManager.addConfig (/<file_path>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/<file_path>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
    at OptionManager.init (/<file_path>/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at File.initOptions (/<file_path>/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/<file_path>/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/<file_path>/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at Babelify._flush (/<file_path>/node_modules/babelify/index.js:27:24)
    at Babelify.<anonymous> (_stream_transform.js:118:12)
➜  accounts git:(develop) ✗ 

```

From what I can see, Babelify is essentially treating `.react.js` as the extension for the file rather than just the trailing `.js` portion and ignoring it during the transform. I haven't tested but may be an issue with others as well, for instance if you have a file named `some.utils.js` it may be ignored for transform as well despite it being a js file.

I'm not sure why this would have started happening after removing all the react require statements throughout the app though...

**Comment by loganfsmyth** [comment]
I'm triaging old issues on babelify. Since this has been inactive for ages, I'm going to close it. Feel free to re-open if there's still something to discuss, but I'm assuming at this point it's been too long to address in a useful way.
