### ISSUE TITLE
Babelify seems to do nothing

### ISSUE THREAD

**Issue by SimonMeskens** [babel/babelify#209]
My outputted browserify bundle is using es6 classes and such, it seems like babelify is not running at all?

Here's my gulpfile:

``` javascript
var gulp = require('gulp');
var sourcemaps = require('gulp-sourcemaps');
var gutil = require("gulp-util");

var watchify = require("watchify");
var browserify = require('browserify');
var tsify = require('tsify');
var uglify = require('gulp-uglify');

var browserSync = require('browser-sync');

var source = require('vinyl-source-stream');
var buffer = require('vinyl-buffer');
var plumber = require('gulp-plumber');
var del = require('del');

var paths = {
    basedir: '.',
    src: 'src',
    entry: '/app.ts',
    bundle: 'app-bundle.js',
    out: './dist'
};

var bundler = browserify({
    basedir: paths.basedir,
    debug: true,
    entries: [paths.src + paths.entry],
    transform: [
        ['babelify', {
            presets: ['es2015'],
            ignore: ['/src/libs/**']
        }]
    ],
    plugin: [watchify, [tsify, { typescript: require('typescript') }]],
    ignore: ['./src/libs/**'],
    cache: {},
    packageCache: {}
});

bundler.on('log', gutil.log);

gulp.task('clean', function () {
    try {
        del.sync(paths.out + '/**/*');
    } catch (err) { }
});

gulp.task('libs', function () {
    return gulp.src([paths.src + '/libs/**'])
        .pipe(plumber())
        .pipe(gulp.dest(paths.out + '/libs'))
});

gulp.task('pages', ['libs'], function () {
    return gulp.src([paths.src + '/**/*.html'])
        .pipe(plumber())
        .pipe(gulp.dest(paths.out));
});

gulp.task('bundle', function () {
    return bundler.bundle()
        .on('error', function (err) {
            gutil.log(err.message);
            browserSync.notify(err.message, 3000);
            this.emit('end');
        })
        .pipe(plumber())
        .pipe(source(paths.bundle))
        .pipe(buffer())
        .pipe(sourcemaps.init({
            loadMaps: true
        }))
        //.pipe(uglify())
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest(paths.out));
});

gulp.task('refresh', ['bundle'], browserSync.reload);

gulp.task('watch', ['pages', 'bundle'], function () {
    var watcher = gulp.watch(paths.src + '/**/*', ['refresh']);
    watcher.on('change', function (event) {
        console.log('File ' + event.path + ' was ' + event.type + ', running tasks...');
    });
});

gulp.task('browser-sync', ['watch'], function () {
    return browserSync({
        server: {
            baseDir: paths.out
        }
    });
});

gulp.task('default', ['browser-sync']);
```

**Comment by gdyrrahitis** [comment]
Same issue here, babelify does not transpile the ES6 code via Node.

```
function bundle(bundler) {
    return bundler
        .plugin(tsify)
        .transform('babelify', { presets: ['es2015'] })
        .bundle()
        .pipe(source("src/client/entry.js"))
        .pipe(buffer())
        .pipe(uglify())
        .on("error", function(e) {
            gutil.log(e);
         })
        .pipe(gulp.dest("dist/"));
}

// I call it like this:
bundle(browserify("./src/client/main.ts"))
```

I have installed:

```
"babel-preset-es2015": "^6.24.1",
"babelify": "^7.3.0",
"gulp-uglify": "^3.0.0",
"browserify": "^13.1.0",
```

I get the following error:
```
{ GulpUglifyError: unable to minify JavaScript
    at createError (D:\Dev\project\node_modules\gulp-uglify\lib\create-error.js:6:14)
    at apply (D:\Dev\project\node_modules\gulp-uglify\node_modules\lodash\_apply.js:16:25)
    at wrapper (D:\Dev\project\node_modules\gulp-uglify\node_modules\lodash\_createCurry.js:41:12)
    at D:\Dev\project\node_modules\gulp-uglify\lib\minify.js:54:15
    at DestroyableTransform._transform (D:\Dev\project\node_modules\gulp-uglify\composer.js:10:23)
    at DestroyableTransform.Transform._read (D:\Dev\project\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (D:\Dev\project\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (D:\Dev\project\node_modules\readable-stream\lib\_stream_writable.js:338:64)
    at writeOrBuffer (D:\Dev\project\node_modules\readable-stream\lib\_stream_writable.js:327:5)
    at DestroyableTransform.Writable.write (D:\Dev\project\node_modules\readable-stream\lib\_stream_writable.js:264:11)
  cause:
{ SyntaxError: Unexpected token: name (BaseController)
       at JS_Parse_Error.get (eval at <anonymous> (D:\Dev\project\node_modules\uglify-js\tools\node.js:21:1), <anonymous>:86:23)
       at formatError (util.js:644:15)
       at formatValue (util.js:550:18)
       at formatProperty (util.js:790:15)
       at util.js:650:12
       at Array.map (native)
       at formatObject (util.js:649:15)
       at formatValue (util.js:589:16)
       at inspect (util.js:183:10)
       at exports.format (util.js:69:24)
     message: 'Unexpected token: name (BaseController)',
     filename: 'src\\client\\entry.js',
     line: 60554,
     col: 6,
     pos: 2039954 },
  plugin: 'gulp-uglify',
  fileName: 'D:\\Dev\\project\\src\\client\\entry.js',
  showStack: false }
```

Snippet from generated code:
```
...
},{}],58:[function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
class BaseController {
    constructor($scope) {
        this.$scope = $scope;
        this.setUniqueId = (id) => {
            this.$scope.controllerId = id;
        };
        $scope.controllerId = undefined;
    }
}
exports.BaseController = BaseController;

},{}],59:[function(require,module,exports){
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const base_controller_1 = require("../base.controller/base.controller");
class HomeController extends base_controller_1.BaseController {
    constructor($scope, $location, $localStorage, socketService, notificationService) {
...
```

Any help?

**Comment by loganfsmyth** [comment]
You'll need

    .transform('babelify', { presets: ['es2015'] })

to be

    .transform('babelify', { presets: ['es2015'], extensions: ['.js', '.ts'] })

since otherwise Babelify has no way to know that you want it to run on Typescript files.
