### ISSUE TITLE
issue in bundle.js when working with browserify in webstorm 

### ISSUE THREAD

**Issue by Sunimali** [babel/babelify#222]
i hv create a bundle.js file for my examlpe.js scripte using `browserify  example.js > bundle.js` in terminal in webstorm.after that i tried to run bundle.js file.but it gives an error like below.
```
"C:\Program Files (x86)\JetBrains\WebStorm 11.0\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" bundle.js
c:\Users\User\WebstormProjects\untitled6\bundle.js:28466
var xhr = new global.XMLHttpRequest();
          ^

TypeError: global.XMLHttpRequest is not a constructor
    at Object.<anonymous> (c:\Users\User\WebstormProjects\untitled6\bundle.js:28466:11)
    at Object.__dirname.155 (c:\Users\User\WebstormProjects\untitled6\bundle.js:28501:4)
    at s (c:\Users\User\WebstormProjects\untitled6\bundle.js:1:316)
    at c:\Users\User\WebstormProjects\untitled6\bundle.js:1:367
    at Object.<anonymous> (c:\Users\User\WebstormProjects\untitled6\bundle.js:28504:18)
    at Object.__dirname.156../capability (c:\Users\User\WebstormProjects\untitled6\bundle.js:28787:4)
    at s (c:\Users\User\WebstormProjects\untitled6\bundle.js:1:316)
    at c:\Users\User\WebstormProjects\untitled6\bundle.js:1:367
    at Object.<anonymous> (c:\Users\User\WebstormProjects\untitled6\bundle.js:28376:21)
    at Object.__dirname.154../lib/request (c:\Users\User\WebstormProjects\untitled6\bundle.js:28455:4)

Process finished with exit code 1
```

**Comment by loganfsmyth** [comment]
1. This doesn't appear to have anything to do with `babelify`.
2. `XMLHttpRequest` isn't a constructor because you are running your code in Node, not in a browser.

**Comment by Sunimali** [comment]
i am new to webstorm and i am following a vedio tutorial.
![capture](https://cloud.githubusercontent.com/assets/22918076/20958720/0936e4b4-bc7d-11e6-8bd4-0bc34b79a9c5.JPG)

it works in that vedio.but when i am doing it it gives me error
