### ISSUE TITLE
Generator  babel

### ISSUE THREAD

**Issue by zhuangdize** [babel/babelify#230]
![image](https://cloud.githubusercontent.com/assets/10000643/23893615/1ce0edd0-08da-11e7-9515-e11692987c5f.png)

this is my .babelrc config
{
  "presets": ["es2015", "react", "stage-0"],
  "plugins": [
    "transform-runtime"
  ]
}

so how can i solve this problem

**Comment by nicferrier** [comment]
I have much the same thing I think. I have this in package.json:

```
  "dependencies": {
    "js-csp": "1.0.1",
    "express": "4.14.0",
    "serve-index": "1.8.0",
    "body-parser": "1.17.1",
    "eventsource": "0.2.2",
    "sse-node": "1.0.2",
    "babel-polyfill": "6.23.0"
  },
  "devDependencies": {
    "deep-equal": "1.0.1",
    "assert-promise": "0.0.3",
    "sha1": "1.1.1",
    "browserify": "10.2.0",
    "eventsource-polyfill": "0.9.6",
    "express-browserify": "1.0.2",
    "babelify": "7.3.0",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-stage-0": "6.24.1",
    "babel-polyfill": "6.23.0",
    "babel-plugin-transform-runtime": "6.23.0",
    "regenerator-runtime": "0.10.5"
  },
```

and I have a browserify piece of code:

```
function () {
  const main_out = fs.createWriteStream("main.js");
  var b = browserify("server.js")
      .transform("babelify", {
        presets: ["es2015"],
        global: true
      })
      .bundle();
  b.pipe(main_out);
}
```

and then the generated code fails like:

```
c:\sandbox\work\repos\nicferrier\cspjs\main.js:4741
var _marked = [player].map(regeneratorRuntime.mark);
                           ^
ReferenceError: regeneratorRuntime is not defined
    at Object.<anonymous> (c:\sandbox\work\repos\nicferrier\cspjs\main.js:4741:28)
    at Object.__dirname.5._process (c:\sandbox\work\repos\nicferrier\cspjs\main.js:4840:4)
    at s (c:\sandbox\work\repos\nicferrier\cspjs\main.js:1:316)
    at e (c:\sandbox\work\repos\nicferrier\cspjs\main.js:1:487)
    at Object.<anonymous> (c:\sandbox\work\repos\nicferrier\cspjs\main.js:1:505)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
```

obviously it's not been pulled in properly.

I tried manually putting it at the start of the file, like:

```
var regeneratorRuntime = require("generator-runtime");
```

on line 1, before any other browserify generated stuff.

That works just dandy.

Obviously one does not want to do that.

Any clue on the solution?

**Comment by hzoo** [comment]
This seems out of date but you either need `babel-polyfill` or transform-runtime plugin with `babel-runtime` as a dep
