### ISSUE TITLE
Using removed Babel 5 option: base.stage - Check out the corresponding stage-x presets

### ISSUE THREAD

**Issue by krainboltgreene** [babel/babelify#238]
I know this issue has come up but I believe this is a unique situation..

  1. I have a babel 6 project
  2. I have a dependency that is a babel 5 project
  3. The dependency is transpiled before publish and it contains both raw and transpiled.

I have tried `only: "source/"` and `ignore: "node_modules/` neither have worked.

Backtrace: 

```
    at Logger.error (/Users/krainboltgreene/Code/laurelandwolf/admin-internal-toolkit/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/krainboltgreene/Code/laurelandwolf/admin-internal-toolkit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:220:20)
    at OptionManager.init (/Users/krainboltgreene/Code/laurelandwolf/admin-internal-toolkit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/krainboltgreene/Code/laurelandwolf/admin-internal-toolkit/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/krainboltgreene/Code/laurelandwolf/admin-internal-toolkit/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/krainboltgreene/Code/laurelandwolf/admin-internal-toolkit/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Babelify._flush (/Users/krainboltgreene/Code/laurelandwolf/admin-internal-toolkit/node_modules/babelify/index.js:27:24)
    at Babelify.<anonymous> (_stream_transform.js:118:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at Babelify.emit (events.js:188:7)
```

**Comment by krainboltgreene** [comment]
Turns out the package has this in the `package.json`:

```

  "browserify": {
    "transform": [
      [
        "babelify",
        {
          "stage": "0"
        }
      ]
    ]
  },
```

Is there anyway to ignore this?

**Comment by loganfsmyth** [comment]
`package.json` `browserify` fields aren't something that babel has control over. I personally think publishing one using `browserify` is a big mistake for just this reason.

**Comment by krainboltgreene** [comment]
I just want to clarify that at the time Babel was *picking up on the field in a node_module for no reason*.

I think that while this issue was closed without understanding the problem, it's probably long gone.

**Comment by jasonfb** [comment]
this happened to me after I inadvertently added `stage: 1` to my `server/.babelrc` file
```
{
  "presets": ["es2015", "stage-0"],
  "plugins": ["transform-runtime"],
   stage: 1
}
```

fixed by removing this

```
{
  "presets": ["es2015", "stage-0"],
  "plugins": ["transform-runtime"],
}
```
