### ISSUE TITLE
Can't find module lodash/cloneDeep

### ISSUE THREAD

**Issue by pedromcarrion** [babel/babelify#250]
When i run gulp after install babelify 7.3.0 i saw the error:

module.js:487
    throw err;
    ^

Error: Cannot find module 'lodash/cloneDeep'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (...\node_modules\babel-template\lib\index.js:57:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

**Comment by loganfsmyth** [comment]
To me this sounds like there was an error during `npm install` or something. That package is in the dependencies, so it should be there. I'd recommend deleting `node_modules` and reinstalling things.
