### ISSUE TITLE
Cannot read property 'transform' of undefined while parsing file

### ISSUE THREAD

**Issue by simonzack** [babel/babelify#54]
`transform` isn't properly exported (`babel.transform` is undefined) and this shows up when using babelify with [isparta](https://github.com/douglasduteil/isparta). Babel 4.5.5 works, 4.6.0 4.6.1 doesn't

    TypeError: Cannot read property 'transform' of undefined while parsing file: test.js
        at Instrumenter.instrumentSync (node_modules\isparta\lib\instrumenter.js:49:37)
        at Instrumenter.instrument (node_modules\isparta\node_modules\istanbul\lib\instrumenter.js:542:37)
        at Stream.<anonymous> (node_modules\browserify-istanbul\index.js:24:20)
        at _end (node_modules\browserify-istanbul\node_modules\through\index.js:65:9)
        at Stream.stream.end (node_modules\browserify-istanbul\node_modules\through\index.js:74:5)
        at Transform.onend (node_modules\browserify\node_modules\module-deps\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:523:10)
        at Transform.g (events.js:199:16)
        at Transform.emit (events.js:129:20)
        at node_modules\browserify\node_modules\module-deps\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
        at process._tickCallback (node.js:355:11)

**Comment by sebmck** [comment]
This is an isparta issue. Related babel/babel#908.

**Comment by simonzack** [comment]
Ah, I'll send a PR there.
