### ISSUE TITLE
lodash error with babelify 5.0.4

### ISSUE THREAD

**Issue by smaye81** [babel/babelify#63]
I am trying to use babelify 5.0.4 with browserify/watchify and receiving the following error:

```
Error: Cannot find module 'lodash/lang/clone'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Dev/Projects/angular-browserify-seed/node_modules/babelify/index.js:2:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```
Here is the task in my Gulpfile that is causing the error:

```
gulp.task('watchify', function () {

    var appBundler = watchify(browserify('./app/app.js', watchify.args));

    appBundler.transform(babelify);

    function rebundle() {
        return appBundler.bundle()
            .pipe(source(appBundleName))
            .pipe(gulp.dest('./app/bundle'));
    }

    appBundler.on('update', rebundle);

    return rebundle();
});
```

**Comment by sebmck** [comment]
Try reinstalling your node modules. `rm -rf node_modules && npm install`.

**Comment by smaye81** [comment]
That seems to have worked, thank you.  Is this an issue with `babelify`, `lodash`, or some other node_module dependency problem?

**Comment by sebmck** [comment]
Great! npm problem probably. You would've upgraded babelify and it would've been referencing an older version of lodash.
