### ISSUE TITLE
Using RegExp for ignore parameter causes TypeError in utils.list

### ISSUE THREAD

**Issue by konistehrad** [babel/babelify#69]
Appeared after the fix for #67. 

```
TypeError: undefined is not a function while parsing file: /Users/conrad/Developer/DateNighto/htmlVN/app/scripts/starfighter.js
    at Object.list (/Users/conrad/Developer/DateNighto/htmlVN/node_modules/babel-core/lib/babel/util.js:105:18)
    at list (/Users/conrad/Developer/DateNighto/htmlVN/node_modules/babel-core/lib/babel/transformation/file/option-parsers.js:41:15)
    at File.normalizeOptions (/Users/conrad/Developer/DateNighto/htmlVN/node_modules/babel-core/lib/babel/transformation/file/index.js:126:31)
    at new File (/Users/conrad/Developer/DateNighto/htmlVN/node_modules/babel-core/lib/babel/transformation/file/index.js:86:22)
    at Object.transform (/Users/conrad/Developer/DateNighto/htmlVN/node_modules/babel-core/lib/babel/transformation/index.js:18:14)
    at Stream.end (/Users/conrad/Developer/DateNighto/htmlVN/node_modules/babelify/index.js:34:25)
    at _end (/Users/conrad/Developer/DateNighto/htmlVN/node_modules/babelify/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/conrad/Developer/DateNighto/htmlVN/node_modules/babelify/node_modules/through/index.js:74:5)
    at Transform.onend (/Users/conrad/Developer/DateNighto/htmlVN/node_modules/browserify/node_modules/module-deps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Transform.g (events.js:199:16)
```

it looks like the ignore RegExp is making it into the utils.list() function and it's just not having it. Thanks again!

**Comment by sebmck** [comment]
What are the options you're passing?

**Comment by konistehrad** [comment]
The relevant bits are:

```
  return browserify({
      debug: true,
    })
    .add(config.jsEntries)
    .transform(babelify.configure({
      ignore:   /(bower_components|vendor)/,
      optional: _6TO5_OPTIONAL,
      loose:    _6TO5_LOOSE,
      modules:  'common'
    }))
```

**Comment by sebmck** [comment]
I'll prepare a fix but In the meantime you can wrap it in an array:

```javascript
  return browserify({
      debug: true,
    })
    .add(config.jsEntries)
    .transform(babelify.configure({
      ignore:   [/(bower_components|vendor)/],
      optional: _6TO5_OPTIONAL,
      loose:    _6TO5_LOOSE,
      modules:  'common'
    }))
```

Or even this which IIRC should work:

```javascript
  return browserify({
      debug: true,
    })
    .add(config.jsEntries)
    .transform(babelify.configure({
      ignore:   ["bower_components/**", "vendor/**"],
      optional: _6TO5_OPTIONAL,
      loose:    _6TO5_LOOSE,
      modules:  'common'
    }))
```

**Comment by konistehrad** [comment]
Great I'll use the second I like that more anyway. Thank you again!

**Comment by konistehrad** [comment]
For your reference: the first workaround worked, while the second one no longer crashed, but didn't respect the ignore property. Thanks again for your help.

**Comment by sebmck** [comment]
No problem! Probably some weird glob behaviour.
